#!/usr/bin/env bash
# docs.bash -- generate docs/justfile.md FROM the Justfile, and prove it current.
#
#   docs.bash --write   regenerate docs/justfile.md
#   docs.bash --check   exit 1 if the committed file has drifted
#
# WHY GENERATED, NOT WRITTEN
# Hand-written command docs rot the moment a recipe is renamed, and nothing
# catches it. The source of truth here is `just --dump --dump-format json`,
# which is the same machine contract the menu and doctor consume. --check runs
# inside `just ci`, so a recipe change that skips `just docs` fails the
# gate instead of shipping a lie.
#
# Pure GNU Bash 5.3+.

# shellcheck source=tools.bash disable=SC2154,SC1091
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/tools.bash"

set -uo pipefail

readonly DOC_REL="docs/justfile.md"
readonly DOC_PATH="$JUST_REPO_DIR/$DOC_REL"

tools_need jq || exit 1

# Render the whole document to stdout. Group order is taken from first
# appearance in the Justfile so the doc reads in the same order as the file.
render() {
  local json
  json=$(just_json) || just_die "just --dump failed"

  printf '# `just` reference\n\n'
  printf '<!-- GENERATED by .just/helpers/docs.bash -- do not edit by hand. -->\n'
  printf '<!-- Regenerate with `just docs`; `just docs-check` gates it in `just ci`. -->\n\n'
  printf 'Every recipe in the ForgeCode Justfile, grouped as the file groups them.\n'
  printf 'Machine-readable form: `just --dump --dump-format json`.\n\n'

  local -a groups
  mapfile -t groups < <(
    printf '%s' "$json" | jq -r '
      .recipes
      | to_entries[]
      | select(.value.private | not)
      | ([.value.attributes[]? | select(type == "object" and has("group")) | .group] | first) // "other"
    ' | awk '!seen[$0]++'
  )

  local g
  for g in "${groups[@]}"; do
    printf '## %s\n\n' "$g"
    printf '| recipe | arguments | what it does |\n'
    printf '|---|---|---|\n'
    # Separator is US (0x1f), not tab. `read` treats tab as IFS whitespace,
    # so consecutive tabs collapse into one and a recipe with no parameters
    # loses a field -- its doc slides into the arguments column.
    printf '%s' "$json" | jq -r --arg g "$g" '
      .recipes
      | to_entries[]
      | select(.value.private | not)
      | select((([.value.attributes[]? | select(type == "object" and has("group")) | .group] | first) // "other") == $g)
      | [
          .key,
          ([.value.parameters[]? | .name + (if .default then "=" + (.default | tostring) else "" end)] | join(" ")),
          ((.value.doc // "") | split("\n") | .[0] | gsub("\\|"; "\\\\|"))
        ]
      | join("\u001f")
    ' | sort | while IFS=$'\x1f' read -r name params doc; do
      printf '| `%s` | %s | %s |\n' "$name" "${params:-–}" "${doc:-–}"
    done
    printf '\n'
  done

  printf '## Dependencies\n\n'
  printf 'Recipes that run other recipes first.\n\n'
  printf '```\n'
  printf '%s' "$json" | jq -r '
    .recipes
    | to_entries[]
    | select(.value.dependencies | length > 0)
    | .key + " <- " + ([.value.dependencies[].recipe] | join(", "))
  ' | sort
  printf '```\n'
}

case "${1:---check}" in
  --write)
    mkdir -p "$(dirname -- "$DOC_PATH")" || exit 1
    render > "$DOC_PATH.tmp" || {
      rm -f -- "$DOC_PATH.tmp"
      just_die "render failed"
    }
    mv -f -- "$DOC_PATH.tmp" "$DOC_PATH"
    printf 'wrote %s\n' "$DOC_REL"
    ;;
  --check)
    if [[ ! -f $DOC_PATH ]]; then
      printf '%s is missing -- run: just docs\n' "$DOC_REL" >&2
      exit 1
    fi
    if diff -u "$DOC_PATH" <(render) > /dev/null 2>&1; then
      printf '%s is current\n' "$DOC_REL"
      exit 0
    fi
    printf '%s has drifted from the Justfile:\n\n' "$DOC_REL" >&2
    diff -u "$DOC_PATH" <(render) | head -40 >&2
    printf '\nfix with: just docs\n' >&2
    exit 1
    ;;
  *)
    printf 'usage: docs.bash {--write | --check}\n' >&2
    exit 2
    ;;
esac
